sabian_symbol_data ={
  Aries:{"0-1 deg Aries": "A Woman Just Risen From The Sea; A Seal Is Embracing Her", "1-2 deg Aries": "A Comedian Reveals Human Nature", "2-3 deg Aries": "The Cameo Profile Of A Man, Suggesting The Shape Of His Country", "3-4 deg Aries": "Two Lovers Strolling On A Secluded Walk", "4-5 deg Aries": "A Triangle With Wings", …}
  Aquarius:{"0-1 deg Aquarius": "An Old Adobe Mission In California", "1-2 deg Aquarius": "An Unexpected Thunderstorm", "2-3 deg Aquarius": "A Deserter From The Navy", "3-4 deg Aquarius": "A Hindu Yogi Demonstrates His Healing Powers", "4-5 deg Aquarius": "A Council Of Ancestors Is Seen Implementing Thee Efforts Of A Young Leader", …}
  Cancer:{"0-1 deg Cancer": "On A Ship The Sailors Lower An Old Flag And Raise A New One", "1-2 deg Cancer": "A Man On A Magic Carpet Hovers Over A Large Area Of Land", "2-3 deg Cancer": "A Man Bundled In Fur Leads A Shaggy Deer", "3-4 deg Cancer": "A Cat Arguing With A Mouse", "4-5 deg Cancer": "At A Railroad Crossing, An Automobile is Wrecked By A Train", …}
  Capricorn:{"0-1 deg Capricorn": "An Indian Chief Claims Power From The Assembled Tribe", "1-2 deg Capricorn": "Three Rose Windows In A Gothic Church, One Damaged By War", "2-3 deg Capricorn": "A Human Soul, In Its Eagerness For New Experiences, Seeks Embodiment", "3-4 deg Capricorn": "A Group Of People Outfitting A Large Canoe At The Start Of A Journey By Water", "4-5 deg Capricorn": "Indians On The Warpath. While Some Men Row A Well-Filled Canoe, Others In It Perform A War Dance", …}
  Gemini:{"0-1 deg Gemini": "A Glass-Bottomed Boat Reveals Undersea Wonders", "1-2 deg Gemini": "Santa Claus Furtively Filling Stockings Hanging In Front Of Fireplace", "2-3 deg Gemini": "The Garden Of The Tuileries In Paris", "3-4 deg Gemini": "Holly And Mistletoe Reawaken Old Memories Of Christmas", "4-5 deg Gemini": "A Revolutionary Magazine Asking For Action", …}
  Leo:{"0-1 deg Leo": "Blood Rushes To A Man’s Head As His Vital Energies Are Mobilized Under The Spur Of Ambition", "1-2 deg Leo": "An Epidemic Of Mumps", "2-3 deg Leo": "A Middle-Aged Woman, Her Long Hair Flowing Over Her Shoulders And In A Braless Youthful Garment", "3-4 deg Leo": "A Formally Dressed Elderly Man Stands Near Trophies He Brought Back From A Hunting Expedition", "4-5 deg Leo": "Rock Formations Tower Over A Deep Canyon", …}
  Libra:{"0-1 deg Libra": "In A Collection Of Perfect Specimens Of Many Biolo…uty Of Its Wings, Its Body Impaled By A Fine Dart", "1-2 deg Libra": "The Transmutation Of The Fruits Of Past Experience… Seed-Realizations Of The Forever Creative Spirit", "2-3 deg Libra": "The Dawn Of A New Day Reveals Everything Changed", "3-4 deg Libra": "Around A Campfire A Group Of Young People Sit In Spiritual Communion", "4-5 deg Libra": "A Man Revealing To His Students The Foundation Of …Knowledge Upon Which A “New World” Could Be Built", …}
  Pisces:{"0-1 deg Pisces": "In A Crowded Marketplace Farmers And Middlemen Display A Great Variety Of Products", "1-2 deg Pisces": "A Squirrel Hiding From Hunters", "2-3 deg Pisces": "Petrified Tree Trunks Lie Broken On Desert Sand", "3-4 deg Pisces": "Heavy Car Traffic On A Narrow Isthmus Linking Two Seashore Resorts", "4-5 deg Pisces": "A Church Bazaar", …}
  Sagittarius:{"0-1 deg Sagittarius": "Retired Army Veterans Gather To Reawaken Old Memories", "1-2 deg Sagittarius": "White-capped Waves Display The Power Of Wind Over Sea", "2-3 deg Sagittarius": "Two Men Playing Chess", "3-4 deg Sagittarius": "A Little Child Learning To Walk With The Encouragement Of His Parents", "4-5 deg Sagittarius": "An Old Owl Sits Alone On The Branch Of A Large Tree", …}
  Scorpio:{"0-1 deg Scorpio": "A Crowded Sightseeing Bus On A City Street", "1-2 deg Scorpio": "A Delicate Bottle Of Perfume Lies Broken, Releasing Its Fragrance", "2-3 deg Scorpio": "A House-Raising Party In A Small Village Enlists The Neighbors’ Cooperation", "3-4 deg Scorpio": "A Youth Carries A Lighted Candle In A Devotional Ritual", "4-5 deg Scorpio": "A Massive Rocky Shore Resist The Pounding Of The Sea", …}
  Taurus:{"0-1 deg Taurus": "A Clear Mountain Stream", "1-2 deg Taurus": "An Electrical Storm", "2-3 deg Taurus": "Natural Steps Lead To A Lawn Of Clover In Bloom", "3-4 deg Taurus": "The Pot Of Gold At The End Of The Rainbow", "4-5 deg Taurus": "A Widow At An Open Grave", …}
  Virgo:{"0-1 deg Virgo": "In A Portrait, The Significant Features Of A Man’s Head Are Artistically Emphasized", "1-2 deg Virgo": "A Large White Cross Dominates The Landscape", "2-3 deg Virgo": "Two Guardian Angels", "3-4 deg Virgo": "Black And White Children Play Together Happily", "4-5 deg Virgo": "A Man Becoming Aware Of Nature Spirits And Normally Unseen Spiritual Agencies", …}
}